<?php

namespace Backend\ProductoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaRepository extends EntityRepository
{
}
